[theme]
base = "light"          # Establece el tema por defecto

# (Opcional) Puedes personalizar colores:
# primaryColor = "#1f77b4"
# backgroundColor = "#fafafa"
# secondaryBackgroundColor = "#e1e1e1"
# textColor = "#262730"
# font = "sans serif"
